GL_FUNC(void, AttachShader, (GLuint, GLuint))
GL_FUNC(void, Clear, (GLbitfield))
GL_FUNC(void, ClearColor, (GLclampf, GLclampf, GLclampf, GLclampf))
GL_FUNC(void, CompileShader, (GLuint))
GL_FUNC(GLuint, CreateProgram, (void))
GL_FUNC(GLuint, CreateShader, (GLenum))
GL_FUNC(void, CullFace, (GLenum))
GL_FUNC(void, DepthMask, (GLboolean))
GL_FUNC(void, DetachShader, (GLuint, GLuint))
GL_FUNC(void, DeleteProgram, (GLuint))
GL_FUNC(void, DeleteShader, (GLuint))
GL_FUNC(void, Disable, (GLenum))
GL_FUNC(void, DrawElements, (GLenum, GLsizei, GLenum, const GLvoid*))
GL_FUNC(void, Enable, (GLenum))
GL_FUNC(void, EnableVertexAttribArray, (GLuint))
GL_FUNC(void, FrontFace, (GLenum))
GL_FUNC(const GLubyte *, GetString, (GLenum))
GL_FUNC(GLenum, GetError, (void))
GL_FUNC(void, GetProgramiv, (GLuint, GLenum, GLint *))
GL_FUNC(void, GetShaderInfoLog, (GLuint, GLsizei, GLsizei *, char *))
GL_FUNC(void, GetShaderiv, (GLuint, GLenum, GLint *))
GL_FUNC(GLint, GetUniformLocation, (GLuint, const char *))
GL_FUNC(void, LinkProgram, (GLuint))
GL_FUNC(void, ShaderSource, (GLuint, GLsizei, const GLchar* const*, const GLint *))
GL_FUNC(void, Uniform3fv, (GLint, GLsizei, const GLfloat *))
GL_FUNC(void, UniformMatrix4fv, (GLint, GLsizei, GLboolean, const GLfloat *))
GL_FUNC(void, UseProgram, (GLuint))
GL_FUNC(void, ValidateProgram, (GLuint))
GL_FUNC(void, VertexAttribPointer, (GLuint, GLint, GLenum, GLboolean, GLsizei, const void *))
GL_FUNC(void, Viewport, (GLint, GLint, GLsizei, GLsizei))
GL_FUNC(GLint, GetAttribLocation, (GLuint, const GLchar *))
GL_FUNC(void, GenBuffers, (GLsizei, GLuint *))
GL_FUNC(void, DeleteBuffers, (GLsizei, GLuint *))
GL_FUNC(void, BindBuffer, (GLenum, GLuint))
GL_FUNC(void, BufferData, (GLenum, GLsizeiptr, const GLvoid *, GLenum))
